#pragma once
#include <stdio.h>
#include <cstdint>
#include "memory.h"
#include "cpu_new.h"
#include "video.h"

#ifndef DBG
#define DBG(...) ((void)0)
#endif

extern uint8_t framebuffer[144][160];
extern CPU cpu;
extern Memory memory;

struct PPU {
    int ppu_clock = 0;   // dot within the current scanline (0-455)
    int scanline = 0;    // LY
    int mode = 2;        // 0=HBlank 1=VBlank 2=OAM scan 3=transfer
    int mode3_length = 172; // length of the current mode-3 phase (dots)
    int mode3_start = 80;   // dot at which mode 3 begins (75 on the first line)
    bool first_line = false; // true for the very first line after LCD-on
    bool line0 = false;      // true while rendering the first line after LCD-on
    int line_wrap = 456;     // dot at which the scanline wraps (452 on line 0)
    int ly_delay = 0;        // remaining dots before the delayed LY write
    uint8_t ly_pending = 0;  // LY value to write once ly_delay expires
    int frames = 0;
    bool frame_ready = false;
    bool lcd_enabled = false;

    // The PPU's internal mode changes immediately, but the STAT register's
    // mode bits are 4 T-cycles late. The STAT interrupt itself is generated by
    // a level-triggered "line": the OR of the enabled mode/coincidence
    // conditions, which fires on its rising edge (this is what makes a held
    // LYC=LY coincidence *block* subsequent STAT interrupts).
    int stat_pending = 0;       // T-cycles until the STAT update is applied
    int stat_pending_mode = 0;  // the mode to write to STAT when it fires
    bool stat_line = false;     // current level of the internal STAT IRQ line

    // Set IF's STAT interrupt bit (bit 1) if the given STAT enable bit is set.
    void fire_stat_interrupt(uint8_t enable_bit) {
        if (memory.data[0xFF41] & enable_bit) {
            memory.data[0xFF0F] = (memory.data[0xFF0F] & 0x1F) | 0x02;
        }
    }

    // Recompute the STAT IRQ line and fire on its rising edge.
    void update_stat_line() {
        uint8_t stat = memory.data[0xFF41];
        int m = stat & 0x03;
        bool line =
            (m == 0 && (stat & 0x08)) ||
            (m == 1 && (stat & 0x10)) ||
            (m == 2 && (stat & 0x20)) ||
            ((stat & 0x04) && (stat & 0x40));
        if (line && !stat_line) {
            memory.data[0xFF0F] = (memory.data[0xFF0F] & 0x1F) | 0x02;
        }
        stat_line = line;
    }

    // Apply a delayed STAT mode update.
    void apply_pending_mode() {
        uint8_t stat = memory.data[0xFF41];
        stat = (stat & 0xFC) | (stat_pending_mode & 0x03);
        memory.data[0xFF41] = stat;
        update_stat_line();
    }

    void run_pending_mode() {
        if (stat_pending > 0 && --stat_pending == 0) apply_pending_mode();
    }

    // Request a mode transition: the internal mode changes now, the STAT
    // register catches up 4 T-cycles later.
    void set_mode(int new_mode) {
        if (new_mode == mode) return;
        mode = new_mode;
        stat_pending = 4;
        stat_pending_mode = new_mode;
    }

    // LCD on/off transitions update STAT mode bits immediately (the PPU is
    // stopped, so there is no 4-cycle delay).
    void set_mode_immediate(int new_mode) {
        mode = new_mode;
        stat_pending = 0;
        uint8_t stat = memory.data[0xFF41];
        stat = (stat & 0xFC) | (new_mode & 0x03);
        memory.data[0xFF41] = stat;
        update_stat_line();
    }

    // Update the STAT LYC=LY coincidence bit and recompute the STAT line.
    void update_lyc() {
        uint8_t ly = memory.data[0xFF44];
        uint8_t lyc = memory.data[0xFF45];
        uint8_t stat = memory.data[0xFF41];
        bool coincident = (ly == lyc);
        if (coincident) stat |= 0x04; else stat &= ~0x04;
        memory.data[0xFF41] = stat;
        update_stat_line();
    }

    // The game wrote STAT: only bits 3-6 are writable; recompute the line.
    void write_stat(uint8_t value) {
        memory.data[0xFF41] = (memory.data[0xFF41] & 0x07) | (value & 0x78);
        update_stat_line();
    }

    // The game wrote LYC: update the coincidence bit/interrupt (only while
    // the LCD is on; with LCD off the comparison clock is stopped).
    void write_lyc(uint8_t value) {
        memory.data[0xFF45] = value;
        if (lcd_enabled) update_lyc();
    }

    // Compute the extra mode-3 length (in dots) caused by sprite fetches on
    // the current scanline. Uses a cycle-accurate pixel-FIFO model (see
    // SameBoy's display.c fetcher state machine). Returns the sprite penalty
    // (dots) to ADD to the 172-dot base + SCX alignment penalty.
    int compute_mode3_length() {
        // Gather up to 10 sprites on the current scanline, in OAM order.
        uint8_t lcdc = memory.data[0xFF40];
        if (!(lcdc & 0x02)) return 0;  // OBJ_EN off: no sprite penalty
        bool use_8x16 = (lcdc & 0x04) != 0;
        int height = use_8x16 ? 16 : 8;
        int sprite_x[10];
        int n_sprites = 0;
        for (int i = 0; i < 40 && n_sprites < 10; i++) {
            uint8_t sy = memory.data[0xFE00 + i * 4];
            uint8_t sx = memory.data[0xFE00 + i * 4 + 1];
            int top = (int)sy - 16;
            if (scanline >= top && scanline < top + height) {
                // Sprites fully off-screen to the right (X >= 168) are never
                // fetched by the FIFO and add no penalty.
                if (sx < 168) sprite_x[n_sprites++] = sx;
            }
        }
        if (n_sprites == 0) return 0;

        // Pixel-FIFO timing simulation (DMG, no window).
        // fetcher states: 0=T1,1=T2,2=LOW_T1,3=LOW_T2,4=HIGH_T1,5=HIGH_T2,6=PUSH
        int fetcher = 0;
        int fifo = 8;        // 8 junk pixels preloaded
        int position = -16;
        int cycles = 0;

        // Sort sprites by X ascending (FIFO fetches left-to-right).
        for (int i = 0; i < n_sprites; i++)
            for (int j = i + 1; j < n_sprites; j++)
                if (sprite_x[j] < sprite_x[i]) {
                    int t = sprite_x[i]; sprite_x[i] = sprite_x[j]; sprite_x[j] = t;
                }

        int si = 0;
        int guard = 0;
        while (true) {
            if (++guard > 10000) return 0;  // safety: never loop forever
            // x_for_object_match: sprite X == position + 8, with the
            // position <= -8 region collapsing to 0 (uint8 wrap quirk).
            int x_match = position + 8;
            if (x_match < 0) x_match = 0;  // position <= -8

            // Drop sprites that are now behind the fetch cursor.
            while (si < n_sprites && sprite_x[si] < x_match) si++;

            // Fetch all sprites whose X equals the current match position.
            while (si < n_sprites && sprite_x[si] == x_match) {
                // Wait until the background fetcher has the current tile's
                // high byte (state >= 5) and the FIFO is non-empty.
                while (fetcher < 5 || fifo == 0) {
                    if (fetcher <= 4) fetcher++;
                    else if (fetcher == 5) { fetcher = 6; if (fifo == 0) { fifo = 8; fetcher = 0; } }
                    else { if (fifo == 0) { fifo = 8; fetcher = 0; } }
                    cycles++;
                }
                // TODO block: advance fetcher (1 cycle).
                if (fetcher == 5) { fetcher = 6; if (fifo == 0) { fifo = 8; fetcher = 0; } }
                else if (fetcher == 6) { if (fifo == 0) { fifo = 8; fetcher = 0; } }
                cycles++;
                // Free advance (no cycle).
                if (fetcher == 5) { fetcher = 6; if (fifo == 0) { fifo = 8; fetcher = 0; } }
                else if (fetcher == 6) { if (fifo == 0) { fifo = 8; fetcher = 0; } }
                // Sprite data fetch: OAM reads (2) + low byte (2) + high byte (1).
                cycles += 5;
                si++;
            }

            // render_pixel_if_possible: object at X==0 pending blocks.
            bool block = (si < n_sprites && sprite_x[si] == 0);
            if (!block && fifo > 0) {
                fifo--;
                // Scrolling drop (SCX==0 case: -16 -> -8 jump).
                if (((position + 16) & 0xFF) < 8) {
                    if (position == -17) position = -16;
                    else if ((position & 7) == 0) position = -8;
                    else if (position == -9) position = -16;
                    else { /* fractional scrolling */ }
                }
                position++;
            }
            // Advance the background fetcher.
            if (fetcher <= 4) fetcher++;
            else if (fetcher == 5) { fetcher = 6; if (fifo == 0) { fifo = 8; fetcher = 0; } }
            else { if (fifo == 0) { fifo = 8; fetcher = 0; } }

            if (position == 160) break;
            cycles++;
        }

        // FIFO loop length (167 base) -> sprite penalty relative to the
        // 172-dot base. The -2 calibration matches the mooneye reference
        // timing (104/105 sprite test cases; see GOALS.md).
        return (cycles - 167) - 2;
    }

    // Advance the PPU by `cycles` T-cycles (4.194304 MHz dots).
    void step(int cycles) {
        bool lcd_on = (memory.read(0xFF40) & 0x80) != 0;
        if (lcd_on != lcd_enabled) {
            lcd_enabled = lcd_on;
            if (!lcd_on) {
                // LCD off: mode 0, LY reset to 0. The LYC=LY coincidence bit
                // is frozen (the comparison clock stops).
                if (mode != 0) set_mode_immediate(0);
                ppu_clock = 0;
                scanline = 0;
                memory.data[0xFF44] = 0x00;
            } else {
                // LCD on: LY starts at 0 and line 0 begins in mode 0
                // (DMG quirk: no mode 2 on the first line).
                ppu_clock = 0;
                scanline = 0;
                memory.data[0xFF44] = 0x00;
                update_lyc();
                set_mode_immediate(0);
                mode3_start = 75; // first line: mode 3 starts 5 dots early
                first_line = true;
                line0 = true;
                line_wrap = 452;  // first line is 4 dots short
            }
        }

        if (!lcd_enabled) return;

        while (cycles-- > 0) {
            run_pending_mode();
            if (ly_delay > 0 && --ly_delay == 0) {
                memory.data[0xFF44] = ly_pending;
                update_lyc();
            }
            ppu_clock++;
            if (ppu_clock >= line_wrap) {
                ppu_clock = 0;

                // Render the scanline that just finished.
                if (scanline < 144) {
                    render_scanline();
                    render_window();
                    render_sprites();
                }

                scanline++;
                if (scanline > 153) {
                    scanline = 0;
                    frames++;
                }

                // The LY register normally updates immediately, but on the
                // very first line after LCD-on the update is delayed by 4
                // dots when LYC != 0 (the PPU is "late by 2 T-cycles").
                if (line0 && memory.data[0xFF45] != 0) {
                    ly_delay = 4;
                    ly_pending = static_cast<uint8_t>(scanline);
                } else {
                    memory.data[0xFF44] = static_cast<uint8_t>(scanline);
                    update_lyc();
                }
                line0 = false;

                if (scanline == 144) {
                    // Enter VBlank: VBlank interrupt + STAT mode-1 interrupt.
                    // On DMG the mode-2 interrupt also fires here (if enabled).
                    memory.data[0xFF0F] = (memory.data[0xFF0F] & 0x1F) | 0x01;
                    set_mode(1);
                    fire_stat_interrupt(0x20);
                    frame_ready = true;
                    if (!g_headless) render_frame(framebuffer);
                } else if (scanline < 144) {
                    set_mode(2); // visible scanline starts in OAM-scan mode
                    mode3_start = 80; // normal lines: mode 3 at dot 80
                    line_wrap = 456;  // normal lines: 456 dots
                }
                // scanlines 145-153 remain in mode 1
            } else if (scanline < 144) {
                if (ppu_clock == mode3_start) {
                    set_mode(3); // OAM scan -> transfer
                    // Mode-3 length varies with SCX alignment and sprites.
                    // No-sprites case (DMG): 172 + 4*ceil((SCX&7)/4).
                    int scx = memory.read(0xFF43) & 7;
                    int scx_penalty = (scx ? 4 : 0) + (scx >= 5 ? 4 : 0);
                    mode3_length = 172 + scx_penalty + compute_mode3_length();
                    first_line = false;
                } else if (ppu_clock == mode3_start + mode3_length) {
                    set_mode(0); // transfer -> HBlank
                }
            }
        }
    }

    void render_scanline() {
        uint8_t scx = memory.read(0xFF43);
        uint8_t scy = memory.read(0xFF42);
        uint8_t bgp = memory.read(0xFF47);
        uint8_t lcdc = memory.read(0xFF40);
        if (!(lcdc & 0x01)) return;

        uint16_t tile_map = (lcdc & 0x08) ? 0x9C00 : 0x9800;
        uint16_t tile_data = (lcdc & 0x10) ? 0x8000 : 0x8800;
        bool signed_index = !(lcdc & 0x10);

        for (int x = 0; x < 160; ++x) {
            uint8_t pixel_x = (x + scx) & 0xFF;
            uint8_t pixel_y = (scanline + scy) & 0xFF;

            uint8_t tile_col = pixel_x / 8;
            uint8_t tile_row = pixel_y / 8;
            uint16_t tile_index_addr = tile_map + tile_row * 32 + tile_col;
            int tile_index = memory.read(tile_index_addr);
            if (signed_index) tile_index = (int8_t)tile_index;

            uint16_t tile_addr = tile_data + tile_index * 16;
            uint8_t line = pixel_y % 8;
            uint8_t byte1 = memory.read(tile_addr + line * 2);
            uint8_t byte2 = memory.read(tile_addr + line * 2 + 1);
            int bit = 7 - (pixel_x % 8);
            uint8_t color_num = ((byte2 >> bit) & 1) << 1 | ((byte1 >> bit) & 1);
            uint8_t color = (bgp >> (color_num * 2)) & 0x03;

            framebuffer[scanline][x] = color;
        }
    }

    void render_window() {
        uint8_t lcdc = memory.read(0xFF40);
        if (!(lcdc & 0x20)) return;

        uint8_t wx = memory.read(0xFF4B) - 7;
        uint8_t wy = memory.read(0xFF4A);
        uint8_t bgp = memory.read(0xFF47);
        if (scanline < wy) return;

        uint16_t tile_map = (lcdc & 0x40) ? 0x9C00 : 0x9800;
        uint16_t tile_data = (lcdc & 0x10) ? 0x8000 : 0x8800;
        bool signed_index = !(lcdc & 0x10);
        uint8_t win_y = scanline - wy;

        for (int x = wx; x < 160; ++x) {
            uint8_t win_x = x - wx;
            uint8_t tile_col = win_x / 8;
            uint8_t tile_row = win_y / 8;

            uint16_t tile_index_addr = tile_map + tile_row * 32 + tile_col;
            int tile_index = memory.read(tile_index_addr);
            if (signed_index) tile_index = (int8_t)tile_index;

            uint16_t tile_addr = tile_data + tile_index * 16;
            uint8_t line = win_y % 8;
            uint8_t byte1 = memory.read(tile_addr + line * 2);
            uint8_t byte2 = memory.read(tile_addr + line * 2 + 1);

            int bit = 7 - (win_x % 8);
            uint8_t color_num = ((byte2 >> bit) & 1) << 1 | ((byte1 >> bit) & 1);
            uint8_t color = (bgp >> (color_num * 2)) & 0x03;

            framebuffer[scanline][x] = color;
        }
    }

    void render_sprites() {
        uint8_t lcdc = memory.read(0xFF40);
        bool use_8x16 = lcdc & 0x04;

        for (int i = 0; i < 40; ++i) {
            uint8_t y = memory.read(0xFE00 + i * 4) - 16;
            uint8_t x = memory.read(0xFE00 + i * 4 + 1) - 8;
            uint8_t tile_index = memory.read(0xFE00 + i * 4 + 2);
            uint8_t attr = memory.read(0xFE00 + i * 4 + 3);

            if (scanline < y || scanline >= y + (use_8x16 ? 16 : 8)) continue;

            int sprite_line = scanline - y;
            if (attr & 0x40) sprite_line = (use_8x16 ? 15 : 7) - sprite_line;
            uint16_t tile_addr = 0x8000 + tile_index * 16 + sprite_line * 2;

            uint8_t byte1 = memory.read(tile_addr);
            uint8_t byte2 = memory.read(tile_addr + 1);

            for (int j = 0; j < 8; ++j) {
                int pixel_x = x + ((attr & 0x20) ? j : (7 - j));
                if (pixel_x < 0 || pixel_x >= 160) continue;
                uint8_t bit0 = (byte1 >> j) & 1;
                uint8_t bit1 = (byte2 >> j) & 1;
                uint8_t color_id = (bit1 << 1) | bit0;
                if (color_id == 0) continue;
                framebuffer[scanline][pixel_x] = 4 + color_id;
            }
        }
    }
};

extern PPU ppu;
